# Generated by Django 4.1.dev20220122153814 on 2022-03-06 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.datetime.now)),
                ('uraian', models.CharField(max_length=200)),
                ('debit', models.IntegerField(default=0)),
                ('kredit', models.IntegerField(default=0)),
                ('saldo', models.IntegerField(default=0)),
            ],
        ),
    ]
